### PR TITLE
Fix change in default behavior for getDocs

### PR DESCRIPTION
**Pull request by KoenLav**
Addresses this comment: https://github.com/Meteor-Community-Packages/meteor-collection-hooks/pull/256/files#diff-f705af36fbc1b19f194e6feefc325f55ae5a03c1dd615306025ac5b5c122bf7fR129

### CODE REVIEW

**Comment by StorytellerCZ** [comment]
@KoenLav I don't seem to be able to see the comment you are referring to. Can you please elaborate.

**Comment by jdgjsag67251** [comment]
@StorytellerCZ, we had an issue with the latest version of this package. Our code assumed (maybe wrongly) that if the `fields` option was set, fields were actually included. Adding that default value broke this assumption. It is not necessarily wrong behavior on your part, but we could see how other users may be affected by this as well.

**Comment by KoenLav** [comment]
@StorytellerCZ sorry, my review was still pending.

**Comment by StorytellerCZ** [comment]
Got it, will release a new version with this once I get back to my computer.

**Review by StorytellerCZ — APPROVED** [review]

**Pull request merged**
