### PR TITLE
Remove underscore + modernize code base

### PR DESCRIPTION
**Pull request by sebakerckhof**
Continuation of: https://github.com/matb33/meteor-collection-hooks/pull/247 with a broader scope to fully modernize the code base.
All tests are passing except in `direct.js` i had to disable some lines for which I think is a transpilation bug.

Note that I did remove some BC stuff for really old versions of Meteor (pre 0.9)

### CODE REVIEW

**Comment by sebakerckhof** [comment]
ping @zimme

**Comment by StorytellerCZ** [comment]
@sebakerckhof  OK, the plan is to merge the other two PRs and Meteor 1.6.1 branch, release and then update this and release as 1.0.

**Comment by StorytellerCZ** [comment]
@sebakerckhof Alright, v0.9.1 has been released. Time to get this moving again.

**Comment by StorytellerCZ** [comment]
Did the update, please check that I haven't done some mistakes in merger. @sebakerckhof Thanks!

**Comment by StorytellerCZ** [comment]
Will have to update lint rules to take care of new features. But I would like to wait on this till we decide in the organization about what rules to use.

**Pull request merged**
