### PR TITLE
#296: After update direct find

### PR DESCRIPTION
**Pull request by jdgjsag67251**
Fixes issue #296

<details>

The after update hooks do not get called if the update modifies the condition in the find operation:

```js
Collection.before.find((userId, selector, options = {}) => {
  selector.removedAt = { $exists: false };

  return true;
});

// This gets called
Collection.before.update((userId, doc) => {
  console.log("Before update", doc);
});

// This does not get called
Collection.after.update((userId, doc) => {
  console.log("After update", doc);
});

Collection.update(someId, { $set: { removedAt: new Date() } });
```

To me it would make sense if the after update hook would use a direct find, bypassing the before find hooks. Or at least give us the option to determine if the find is used to run the after update hooks.

</details>

### CODE REVIEW

**Review by StorytellerCZ — APPROVED** [review]
LGTM

**Comment by StorytellerCZ** [comment]
Just one little thing. Can you add info about this into the readme. Thanks!

**Review by KoenLav — APPROVED** [review]

**Comment by jdgjsag67251** [comment]
Thanks! I've updated the readme.

**Comment by StorytellerCZ** [comment]
Published in matb33:collection-hooks@1.2.2

**Pull request merged**
